"""empty message

Revision ID: 50a15f1d4bc0
Revises: 94b7e9671c40
Create Date: 2016-01-28 20:59:19.735968

"""

# revision identifiers, used by Alembic.
revision = '50a15f1d4bc0'
down_revision = '94b7e9671c40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_task_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('break_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associated_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_tasks', 'completed_later',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.drop_table('task_breaks')
    ### end Alembic commands ###
