"""empty message

Revision ID: 78976d76a952
Revises: 8131b2eb96af
Create Date: 2016-01-19 22:18:48.290815

"""

# revision identifiers, used by Alembic.
revision = '78976d76a952'
down_revision = '8131b2eb96af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_tasks') as batch_op:
        batch_op.add_column(sa.Column('completed_later', sa.Boolean(), nullable=False,
                                      server_default='false', default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_tasks', 'completed_later')
    ### end Alembic commands ###
