"""empty message

Revision ID: 8131b2eb96af
Revises: fa9874dad3ba
Create Date: 2016-01-14 18:29:54.029723

"""

# revision identifiers, used by Alembic.
revision = '8131b2eb96af'
down_revision = 'fa9874dad3ba'

from alembic import op
import sqlalchemy as sa
import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creation_time', sa.DateTime(), nullable=True))

    connection = op.get_bind()
    tasks = connection.execute('SELECT id FROM tasks')

    for task in tasks:
        earliest_completion = connection.execute(
            'SELECT completed_time FROM completed_tasks '
            'WHERE completed_tasks.associated_task_id == :task_id '
            'ORDER BY completed_tasks.completed_time ASC LIMIT 1',
            task_id=task[0],
        ).fetchone()
        if earliest_completion is None:
            current_day = datetime.date.today()
            midnight = datetime.datetime.min.time()
            current_day = datetime.datetime.combine(current_day, midnight)
            earliest_completion = current_day
        else:
            earliest_completion = earliest_completion[0]
        connection.execute(
            'UPDATE tasks SET creation_time = :creation '
            'WHERE tasks.id == :task_id',
            creation=earliest_completion,
            task_id=task[0],
        )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'creation_time')
    ### end Alembic commands ###
