"""empty message

Revision ID: 94b7e9671c40
Revises: c7a4709f6992
Create Date: 2016-01-22 20:04:14.353335

"""

# revision identifiers, used by Alembic.
revision = '94b7e9671c40'
down_revision = 'c7a4709f6992'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_administration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_user_registrations', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_tasks', 'completed_later',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.drop_table('site_administration')
    ### end Alembic commands ###
