"""empty message

Revision ID: c7a4709f6992
Revises: 78976d76a952
Create Date: 2016-01-21 21:50:18.118408

"""

# revision identifiers, used by Alembic.
revision = 'c7a4709f6992'
down_revision = '78976d76a952'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finish_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'finish_time')
    ### end Alembic commands ###
