"""empty message

Revision ID: fa9874dad3ba
Revises: bd4e6e072d6c
Create Date: 2016-01-12 22:23:13.763910

"""

# revision identifiers, used by Alembic.
revision = 'fa9874dad3ba'
down_revision = 'bd4e6e072d6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Set the default to the first user. At this point we don't support
    # deleting users, so if there are any tasks then that ID will exist unless
    # someone has messed around with the DB by hand. As this is probably only
    # in use by one person at the moment this should be safe.
    with op.batch_alter_table('completed_tasks') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_foreign_key('fk_completed_tasks_users', 'users', ['owner_id'], ['id'])
    with op.batch_alter_table('goals') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_foreign_key('fk_goals_users', 'users', ['owner_id'], ['id'])
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default="1"))
        batch_op.create_foreign_key('fk_tasks_users', 'users', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'owner_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'owner_id')
    op.drop_constraint(None, 'completed_tasks', type_='foreignkey')
    op.drop_column('completed_tasks', 'owner_id')
    ### end Alembic commands ###
